# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4LoginInvalidUsernameNULLPassword():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4LoginInvalidUsernameNULLPassword(self):
    # Test name: 4_Login_Invalid Username_NULL Password
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.saucedemo.com/")
    # 2 | setWindowSize | 1050x718 | 
    self.driver.set_window_size(1050, 718)
    # 3 | click | css=*[data-test="username"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    # 4 | type | css=*[data-test="username"] | username
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("username")
    # 5 | click | css=*[data-test="login-button"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    # 6 | click | css=*[data-test="error"] | 
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").click()
    # 7 | assertText | css=*[data-test="error"] | Epic sadface: Password is required
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").text == "Epic sadface: Password is required"
    # 8 | close |  | 
    self.driver.close()
  
